import type { Metadata, Viewport } from "next";
import "./globals.css";

/**
 * ★Web フォントを読み込まない（docs/spec.md §13-4・§13-6 d）。
 *   フォントはシステムフォントのみ。指定は globals.css の
 *   --font-ja / --font-en に集約してある。
 *
 * title / description / lang は STEP 7 の作業なのでここでは触らない。
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * ★`viewportFit: "cover"` が無いと `env(safe-area-inset-*)` は常に 0 を返す
 *   （2026-08-17 実機確認で発覚）。Dock の下余白がホームバーぶんを
 *   確保できていなかった。Next.js の既定 viewport には viewport-fit が入らない。
 *
 * ★cover にすると描画領域がホームバーの下まで広がるので、
 *   下端に触るものを置くコンポーネント（Dock）は必ず
 *   env(safe-area-inset-bottom) を padding に足すこと。
 */
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
