import type { Metadata } from "next";
import "./globals.css";

/**
 * ★Web フォントを読み込まない（docs/spec.md §13-4・§13-6 d）。
 *   フォントはシステムフォントのみ。指定は globals.css の
 *   --font-ja / --font-en に集約してある。
 *
 * title / description / lang は STEP 7 の作業なのでここでは触らない。
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
